branches:
  only:
  - master
addons:
  homebrew:
    taps: discoteq/discoteq
    packages:
      - bash
      - make
      - lhasa
      - flex
      - gettext
      - texinfo
      - flock
      # needed but already installed : gcc autoconf wget gmp mpfr libmpc
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: c
      before_install:
        - sudo apt-get install -y make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext texinfo
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
          #    - os: osx
          #osx_image: xcode10.2
          #sudo: required
          #language: c
          #before_install:
          #- sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
script:
 - if [ "${TRAVIS_OS_NAME}" == "osx" ];
   then
     export CC=gcc-8;
     export CXX=g++-8;
     (gmake -j3 min &); while [ ! -f $(realpath build-Darwin)/gcc/_libgcc_done ]; do date; sleep 60; done;
   else
     make min -j3;
   fi
 - tar czf amiga-gcc-${TRAVIS_OS_NAME}.tgz /opt/amiga
 - ls -l
after_failure:
  - cat log/*.log
before_deploy:
 - git config --local user.name "bebbo@travis-ci"
 - git config --local user.email "bebbo@bejy.net"
 - export TRAVIS_TAG=latest-$(date +'%Y%m%d%H%M%S')
 - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: ahFeqlMYR6x9DA01B4NeBAqNKqv+ZxJoM0fpQrCzeKI+szah6M3THhhP8XO/PTBhUbM865wpoVg5J+l7GxFtH/Q7AB2wA1sEhpt79FhT4j43Ek8h5E18GKG9UGVZWRLDfhor6ewo3gjf8Q8Tw14MH5H4qdXbxQIHyU3PWoBuIX2Z63/8ad2CWAcSiAaqpK4wzKqR73cjHEH8xHJp5+Q1e5kEsvlksbu95pEVPqndpQ/9HUetwqgR/U6A0dPdY4GcQM8AX17SmvzbXrAOqRhegOg2/j2FnKa/w2m8WD89CxRDW/roRgCOOTe0JleBVqZzuLNaPHu/aRnTSC7wt4SfDbh/WVp1XfZKI5Y49evaljzx11C5PWpqaUk9n3ITg9bGxXcNbgYKo96S6chR33mlBdZWDt/3bWeQGp+liNiUMM57kRpxsLNP3yMNkvxVxAIJ/xMe+FWUJuKwMD/dLDNuTS+vqH0ezLAbuwWLn92G/9OPw24CRrusZ7OPQuZFenDBBj0kM4+1n11JksGgPwF43hPJbXs6u6CQAxVeYYzCMziF3klidoIqiFKz4cmyvxB73cWqRBGP2cr+qworJp41pNnazklRAgVUgoxqWLUNEqHzJ+qU21T1EpoaYXqdcMEv5SBQhOpv/bQmSXU25MGA7VlMrnxTziqVvztKZcA0jyo=
  file: amiga-gcc-${TRAVIS_OS_NAME}.tgz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
after_failure:
  - cat log/*.log
